name: Build PyLabel macOS Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      - name: Create install.sh script
        run: |
          mkdir -p Scripts
          cat << 'EOF' > Scripts/install.sh
          #!/bin/bash

          # Set the installation directory to User's Applications
          PROGRAM_FILES="/Applications/PyLabel"

          # Create the directory if it doesn't exist
          if [ ! -d "$PROGRAM_FILES" ]; then
              mkdir -p "$PROGRAM_FILES"
          fi

          # Copy application files
          cp -R "${0%/*}/PyLabelProgramFiles/" "$PROGRAM_FILES/"

          # Grant permissions
          chmod -R 755 "$PROGRAM_FILES"

          # Check for Python 3.11.9
          found_python=false
          for py_path in $(which -a python3); do
              py_version=$($py_path --version 2>&1)
              if [[ $py_version == "Python 3.11.9" ]]; then
                  found_python=true
                  break
              fi
          done

          if [ "$found_python" = true ]; then
              # Install dependencies
              "$py_path" -m ensurepip
              "$py_path" -m pip install --upgrade pip
              "$py_path" -m pip install -r "$PROGRAM_FILES/requirements.txt"

              # Set up PyLabel command
              echo "#!/bin/bash" > /usr/local/bin/PyLabel
              echo "\"$py_path\" \"$PROGRAM_FILES/PyLabel.py\" \"\$@\"" >> /usr/local/bin/PyLabel
              chmod +x /usr/local/bin/PyLabel
          else
              echo "Python 3.11.9 is not installed."
              open "$PROGRAM_FILES/PyInstructions.pdf"
              exit 1
          fi

          echo "Installation complete. You can now use the command 'PyLabel' from any directory"
          EOF
          chmod +x Scripts/install.sh

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r PyLabelProgramFiles/requirements.txt

      - name: List files before pkgbuild
        run: |
          echo "Listing files before pkgbuild:"
          ls -la
          ls -la PyLabelProgramFiles

      - name: Create the component package
        run: |
          pkgbuild --root PyLabelProgramFiles \
                   --scripts Scripts \
                   --identifier com.LevittConsultingPtyLtd.pylabel \
                   --version 1.0 \
                   --install-location /Applications/PyLabel \
                   MacInstall.pkg

      - name: List files after pkgbuild
        run: |
          echo "Listing files after pkgbuild:"
          ls -la
          ls -la PyLabelProgramFiles

      - name: Create distribution.xml
        run: |
          cat << 'EOF' > distribution.xml
          <?xml version="1.0" encoding="utf-8"?>
          <installer-gui-script minSpecVersion="1">
              <title>PyLabel Installer</title>
              <options customize="never" require-scripts="true"/>
              <choices-outline>
                  <line choice="default">
                      <line choice="pylabel"/>
                  </line>
              </choices-outline>
              <choice id="default"/>
              <choice id="pylabel" visible="false" title="PyLabel">
                  <pkg-ref id="com.LevittConsultingPtyLtd.pylabel"/>
              </choice>
              <pkg-ref id="com.LevittConsultingPtyLtd.pylabel" version="1.0" onConclusion="none">file:./MacInstall.pkg</pkg-ref>
          </installer-gui-script>
          EOF

      - name: List files before productbuild
        run: |
          echo "Listing files before productbuild:"
          ls -la
          ls -la PyLabelProgramFiles

      - name: Build the final package
        run: |
          productbuild --distribution distribution.xml \
                       --resources Resources \
                       --package-path . \
                       --version 1.0 \
                       MacInstall.pkg

      - name: List files after productbuild
        run: |
          echo "Listing files after productbuild:"
          ls -la
          ls -la PyLabelProgramFiles

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit and push .pkg file
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add PyLabelInstaller.pkg
          git commit -m "Add PyLabelInstaller.pkg"
          git push -u origin main
